name: sanatize-commnit
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  check-commit:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for correct naming scheme
        id: checkNaming
        shell: pwsh
        run: .github/workflows/scripts/sanitize-commit/sanitize-commit.ps1
        env:
          gitHubHost: ${{ github.server_url}}
          repoPath: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          prPath: ${{ github.ref }}