name: sanatize-commnit
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  check-commit:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Check for correct naming scheme
        id: checkNaming
        shell: pwsh
        run: .github/workflows/scripts/release-and-publish/determineReleaseType.ps1
        env:
          trigger: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          prUrl: ${{ github.ref }}